# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

name = "Strellio SmartBot"
client_id = "dedcf8c686fcb13d6f4e800609e79747"
application_url = "https://smartbotapi.strellio.co/shopify/install"
embedded = false

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
use_legacy_install_flow = true

[auth]
redirect_urls = [
  "https://smartbotapi.strellio.co/shopify/callback",
  "http://smartbotapi.strellio.co/shopify/callback",
  "http://localhost:4008/shopify/callback"
]

[webhooks]
api_version = "2023-10"

  [webhooks.privacy_compliance]
  customer_deletion_url = "https://smartbotwebhooks.strellio.co/webhooks/shopify/customers/redact"
  customer_data_request_url = "https://smartbotwebhooks.strellio.co/webhooks/shopify/customers/data_request"
  shop_deletion_url = "https://smartbotwebhooks.strellio.co/webhooks/shopify/shop/redact"

[pos]
embedded = false
