version: 2
jobs:
  build:
    deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
              git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git master