version: 2
jobs:
  build:
    deploy:
    docker:
      - image: circleci/node:12.18.3
    steps:
      - checkout
      - run:
          name: Deploy Master to Heroku
          command: |
               if [ "${CIRCLE_BRANCH}" == "master" ]; then
                  npx @banphlet/herokudep start -t ${HEROKU_API_KEY}
               fi