name: Deploy API Backend Service
on:
  workflow_dispatch:
  push:
    branches:
      - master
    # paths:
    #   - 'backend/api/users/**'
jobs:
  build_setup:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    strategy:
      matrix:
        node-version: [20.x]
    steps:
      - shell: bash
        run: |
          echo Running Flow
  call-workflow-passing-data:
    name: Build Service
    uses: ./.github/workflows/deploy_backend_service.yaml
    with:
      SERVICE_NAME: api
      WORKING_DIR: ./
      ENV_FILE_BASE64_SECRET_NAME: ENV_BASE64_STRING
    secrets: inherit