name: Deploy Backend Service
on:
  workflow_call:
    inputs:
      SERVICE_NAME:
        required: true
        type: string
      WORKING_DIR:
        required: true
        type: string
      ENV_FILE_BASE64_SECRET_NAME:
        required: true
        type: string
      GOOGLE_APPLICATION_CREDENTIALS_FILE_NAME:
        default: service-account-dev.json
        required: false
        type: string
      GOOGLE_APPLICATION_CREDENTIALS_BASE64_SECRET_NAME:
        default: GOOGLE_APPLICATION_CREDENTIALS_BASE64
        required: false
        type: string
jobs:
  build_setup:
    runs-on: "ubuntu-latest"
    permissions:
      contents: "read"
      id-token: "write"
    strategy:
      matrix:
        node-version: [19.x]
    steps:
      - shell: bash
        run: |
          echo Build ${{ inputs.SERVICENAME }} > build_log.txt
      - name: Upload build log
        uses: actions/upload-artifact@v3
        with:
          name: build_setup
          path: build_log.txt
  call-workflow-passing-data:
    name: Build Service
    needs: build_setup
    uses: ./.github/workflows/deploy_to_cloud_run.yaml
    with:
      PROJECT_NUMBER: 530345774393
      PROJECT_ID: strellio
      SERVICE_NAME: ${{ inputs.SERVICE_NAME }}
      WORKING_DIR: ${{ inputs.WORKING_DIR }}
      GOOGLE_APPLICATION_CREDENTIALS_FILE_NAME: ${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_FILE_NAME }}
      GOOGLE_APPLICATION_CREDENTIALS_BASE64_SECRET_NAME: ${{ inputs.GOOGLE_APPLICATION_CREDENTIALS_BASE64_SECRET_NAME }}
      ENV_FILE_BASE64_SECRET_NAME: ${{ inputs.ENV_FILE_BASE64_SECRET_NAME }}
      POOL_PROVIDER: dev-provider
    secrets: inherit